name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: macOS-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Force Xcode 14.2
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app
      - name: Version
        run: swift --version
      - name: Test
        run: |
          cd Sources/Core
          swift test
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.7
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          cd Sources/Core
          swift test
